name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            echo "naviage to app directory"
            cd ~/app

            echo "pull latest code"
            git pull origin main

            echo "stop existing container"
            docker stop cicdapp || true

            echo "remove container"
            docker rm cicdapp || true
            
            echo "build new docker image"
            docker build -t cicdapp . && docker rm -f cicdapp || true && docker run -d -p 3000:3000 --name cicdapp cicdapp

            echo "Deployment completed" 
